services:
  bot:
    build:
      context: .
    image: mansoooor/diplom-bot:llm-01
    environment:
      - DB=db
      - BOT_TOKEN=${BOT_TOKEN}
      - KFU_URL=${KFU_URL}
      - KFU_SUB_PATH=${KFU_SUB_PATH}
      - KFU_ACCESS_KEY=${KFU_ACCESS_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SENDER_EMAIL=${MAIL_SENDER_EMAIL}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - LLM_URL=llm:11434
      - LLM_SUB_PATH=v1/chat/
      - LLM_MODEL_NAME=saiga
    restart: always
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:alpine3.19
    environment:
      - POSTGRES_DB=qwerty
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  llm:
    image: ollama/ollama
    volumes:
      - llm-data:/root/.ollama
      - ./llama:/llama/
      - llm-model:/model/
    entrypoint: sh -c /llama/init.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  db-data:
  llm-data:
  llm-model:
