services:
  db:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qwerty
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - db-data:/var/lib/postgresql/data
  llm:
    image: ollama/ollama
    volumes:
      - llm-data:/root/.ollama
      - ./llama:/llama/
      - llm-model:/model/
    entrypoint: sh -c /llama/init.sh
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  db-data:
  llm-data:
  llm-model:
