version: "3.8"

services:
  bot:
    build:
      context: .
    image: mansoooor/diplom-bot
    environment:
      - DB=db
      - BOT_TOKEN=${BOT_TOKEN}
      - KFU_URL=${KFU_URL}
      - KFU_SUB_PATH=${KFU_SUB_PATH}
      - KFU_ACCESS_KEY=${KFU_ACCESS_KEY}
    restart: always
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qwerty
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
