spring:
  docker:
    compose:
      file: docker-compose-local.yml
  application:
    name: mansur-dis-bot
  datasource:
    url: jdbc:postgresql://${DB:localhost}:5432/qwerty
    username: qwerty
    password: qwerty
logging:
  level:
    com:
      example: DEBUG
