CREATE TABLE key_word
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key_word       VARCHAR(255),
    weight         INTEGER                                 NOT NULL,
    dis_problem_id BIGINT,
    CONSTRAINT pk_keyword PRIMARY KEY (id)
);

ALTER TABLE key_word
    ADD CONSTRAINT FK_KEYWORD_ON_DIS_PROBLEM FOREIGN KEY (dis_problem_id) REFERENCES dis_problem (id);
