CREATE TABLE ias_problem
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_ias_problem PRIMARY KEY (id)
);

ALTER TABLE ias_problem
    ADD CONSTRAINT FK_IAS_PROBLEM_ON_ID FOREIGN KEY (id) REFERENCES dis_problem (id);



CREATE TABLE ias_module
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    problem_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_ias_module PRIMARY KEY (id)
);

ALTER TABLE ias_module
    ADD CONSTRAINT FK_IAS_MODULE_ON_PROBLEM FOREIGN KEY (problem_id) REFERENCES ias_problem (id);



CREATE TABLE ias_service
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    group_needed    BOOLEAN                                 NOT NULL,
    applicant_name  VARCHAR(255),
    additional_info VARCHAR(255),
    ias_module_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_ias_service PRIMARY KEY (id)
);

ALTER TABLE ias_service
    ADD CONSTRAINT FK_IAS_SERVICE_ON_IAS_MODULE FOREIGN KEY (ias_module_id) REFERENCES ias_module (id);
